'use client';

import * as React from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import {
  ArrowLeft,
  FileText,
  Quote,
  Lightbulb,
  ListChecks,
  Tag,
  Hash,
  Smile,
  Meh,
  Frown,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useSummary, useVideo } from '@/lib/queries';

function SentimentPill({ sentiment }: { sentiment?: string | null }) {
  const s = (sentiment ?? 'neutral').toLowerCase();
  const map: Record<string, { icon: React.ReactNode; cls: string }> = {
    positive: { icon: <Smile className="h-4 w-4" />, cls: 'bg-success/15 text-success' },
    negative: { icon: <Frown className="h-4 w-4" />, cls: 'bg-destructive/15 text-destructive' },
    neutral: { icon: <Meh className="h-4 w-4" />, cls: 'bg-muted text-muted-foreground' },
    mixed: { icon: <Meh className="h-4 w-4" />, cls: 'bg-warning/15 text-warning' },
  };
  const v = map[s] ?? map.neutral;
  return (
    <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-sm font-medium capitalize ${v.cls}`}>
      {v.icon}
      {s}
    </span>
  );
}

function ListSection({
  title,
  icon,
  items,
  ordered,
}: {
  title: string;
  icon: React.ReactNode;
  items?: string[] | null;
  ordered?: boolean;
}) {
  if (!items || items.length === 0) return null;
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          {icon}
          {title}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <ul className={ordered ? 'list-decimal space-y-2 pl-5' : 'space-y-2'}>
          {items.map((item, i) => (
            <li key={i} className="text-sm leading-relaxed text-foreground/90">
              {!ordered && <span className="mr-2 text-primary">•</span>}
              {item}
            </li>
          ))}
        </ul>
      </CardContent>
    </Card>
  );
}

export default function SummaryPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const { data: video } = useVideo(id);
  const { data: summary, isLoading, isError } = useSummary(id);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <Link href="/queue">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="h-5 w-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-xl font-bold tracking-tight">
              {video?.video_title ?? 'AI Summary'}
            </h1>
            <p className="text-sm text-muted-foreground">{video?.channel_name}</p>
          </div>
        </div>
        <Link href={`/transcripts/${id}`}>
          <Button variant="outline">
            <FileText className="h-4 w-4" /> View Transcript
          </Button>
        </Link>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-40 w-full" />
          <Skeleton className="h-32 w-full" />
        </div>
      ) : isError || !summary ? (
        <Card>
          <CardContent className="py-16 text-center text-sm text-muted-foreground">
            Summary not generated yet.
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 lg:grid-cols-2">
          <Card className="lg:col-span-2">
            <CardHeader className="flex-row items-center justify-between">
              <CardTitle className="text-base">Executive Summary</CardTitle>
              <SentimentPill sentiment={summary.sentiment} />
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed text-foreground/90">{summary.summary}</p>
              {summary.model && (
                <p className="mt-3 text-xs text-muted-foreground">Generated by {summary.model}</p>
              )}
            </CardContent>
          </Card>

          <ListSection
            title="Key Discussion Points"
            icon={<ListChecks className="h-4 w-4 text-primary" />}
            items={summary.key_points}
          />
          <ListSection
            title="Key Insights"
            icon={<Lightbulb className="h-4 w-4 text-warning" />}
            items={summary.key_insights}
          />
          <ListSection
            title="Important Quotes"
            icon={<Quote className="h-4 w-4 text-primary" />}
            items={summary.quotes}
          />
          <ListSection
            title="Action Items"
            icon={<ListChecks className="h-4 w-4 text-success" />}
            items={summary.action_items}
            ordered
          />

          {(summary.topics?.length || summary.keywords?.length || summary.tags?.length) ? (
            <Card className="lg:col-span-2">
              <CardHeader>
                <CardTitle className="text-base">Topics, Keywords &amp; Tags</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {summary.topics && summary.topics.length > 0 && (
                  <div>
                    <p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                      <Hash className="h-3.5 w-3.5" /> Topics
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {summary.topics.map((t, i) => (
                        <Badge key={i} variant="secondary">{t}</Badge>
                      ))}
                    </div>
                  </div>
                )}
                {summary.keywords && summary.keywords.length > 0 && (
                  <div>
                    <p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                      <Tag className="h-3.5 w-3.5" /> Keywords
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {summary.keywords.map((k, i) => (
                        <Badge key={i} variant="outline">{k}</Badge>
                      ))}
                    </div>
                  </div>
                )}
                {summary.tags && summary.tags.length > 0 && (
                  <div>
                    <p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                      <Tag className="h-3.5 w-3.5" /> Tags
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {summary.tags.map((t, i) => (
                        <Badge key={i}>{t}</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ) : null}
        </div>
      )}
    </div>
  );
}
